Task01_Duletov
Duletov/formal_languages pull request #1
Opened 2020-09-08 20:41 UTC by Duletov

2020-09-09 11:12 UTC, gsvgit requested changes

2020-09-09 11:12 UTC, gsvgit commented on README.md
> +### Formal Language Theory
Забыли бейджик со статусом CI и ссылкой на него.

2020-09-09 16:53 UTC, Duletov commented on README.md
> +### Formal Language Theory
Добавил

2020-09-10 08:46 UTC, gsvgit approved these changes
Ок, зачтено.

2020-09-14 10:49 UTC, merged