Task02_Duletov
Duletov/formal_languages pull request #2
Opened 2020-09-16 15:13 UTC by Duletov

2020-09-16 16:52 UTC, gsvgit requested changes

2020-09-16 16:52 UTC, gsvgit commented on Graph.py
> +        for k in range(self.n_vertices):
А Вы злодей. В большинстве реальных случаев будет очень много лишних произведений.

2020-09-16 16:52 UTC, gsvgit commented on main.py
> +    adj = graph.transitive_closure()
Такое ощущение, что эти  строк у Вас несколько раз повторяются. Их точно нельзя как-то вынести в отдельную функцию?

2020-09-16 16:52 UTC, gsvgit commented on tests/test_task02.py
> +def test_intersect():
Всего один тест? А точно всё хорошо с пустым графом? А с парарллельными рёбрами? а если автомат всего с одним состоянием?

2020-09-16 18:58 UTC, Duletov commented on Graph.py
> +        for k in range(self.n_vertices):
Добавил проверку

2020-09-16 18:58 UTC, Duletov commented on main.py
> +    adj = graph.transitive_closure()
Слил три функции в одну

2020-09-16 18:59 UTC, Duletov commented on tests/test_task02.py
> +def test_intersect():
Добавил тестов

2020-09-17 08:17 UTC, gsvgit approved these changes
Ок.

2020-09-19 17:53 UTC, merged