Task05
Duletov/formal_languages pull request #5
Opened 2020-10-13 11:22 UTC by Duletov

2020-10-14 10:56 UTC, gsvgit requested changes
Ну и в тесты надо побольше нетривиальных случаев с грамматиками с эпсилон-правилами.

2020-10-14 10:56 UTC, gsvgit commented on CFG.py
> +        if self.generate_epsilon():
Выглядит странно. Если рекурсивный автомат строится правильно, то дополнительной обработки эпсилонов не требуется.

2020-10-14 11:39 UTC, Duletov commented on CFG.py
> +        if self.generate_epsilon():
Я делал по алгоритму из конспекта (стр 86) и там в строках 9-10 идёт добавление таких петель. В моём понимании эта обработка нужна, к тому же без неё не работает)

2020-10-14 11:40 UTC, Duletov commented
> Ну и в тесты надо побольше нетривиальных случаев с грамматиками с эпсилон-правилами.

Добавил к двум имеющимся ещё один, надеюсь грамматика достаточно нетривиальна.

2020-10-15 08:15 UTC, gsvgit approved these changes
Ок. пожалуй, попытку снимать не буду.

2020-10-15 08:15 UTC, gsvgit commented on CFG.py
> +        if self.generate_epsilon():
Ок. Убедили!

2020-10-16 21:12 UTC, merged